# Generated by Django 4.2.20 on 2025-04-08 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('identity_document', models.CharField(max_length=20, verbose_name='Documento de identidad')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso mensual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En Revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto inicial')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuota mensual')),
                ('term', models.IntegerField(verbose_name='Plazo (meses)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('documents', models.JSONField(blank=True, null=True, verbose_name='Documentos requeridos')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Cliente')),
                ('financing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financing.financingplan', verbose_name='Plan de financiamiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-application_date'],
            },
        ),
    ]
