# Generated by Django 4.2.20 on 2025-05-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='Perfil completo'),
        ),
    ]
