# Generated by Django 4.2.20 on 2025-04-08 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('plan_type', models.CharField(choices=[('programada', 'Compra Programada'), ('credito', 'Crédito Inmediato')], max_length=20, verbose_name='Tipo de plan')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('min_initial_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje inicial mínimo')),
                ('max_initial_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje inicial máximo')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés anual')),
                ('min_term', models.IntegerField(verbose_name='Plazo mínimo (meses)')),
                ('max_term', models.IntegerField(verbose_name='Plazo máximo (meses)')),
                ('adjudication_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje para adjudicación')),
                ('benefits', models.TextField(verbose_name='Beneficios')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('icon', models.CharField(default='fa-money-bill', max_length=50, verbose_name='Ícono (FontAwesome)')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='plans/', verbose_name='Imagen de banner')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan de Financiamiento',
                'verbose_name_plural': 'Planes de Financiamiento',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del producto')),
                ('initial_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje inicial')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto inicial')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuota mensual')),
                ('term', models.IntegerField(verbose_name='Plazo (meses)')),
                ('simulation_data', models.JSONField(verbose_name='Datos completos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financing.financingplan', verbose_name='Plan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Simulación',
                'verbose_name_plural': 'Simulaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
