# Generated by Django 4.2.10 on 2025-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0002_calculatormode'),
    ]

    operations = [
        # Crear modelo PaymentMethod
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del método')),
                ('payment_type', models.CharField(
                    choices=[
                        ('bank_transfer', 'Transferencia Bancaria'),
                        ('mobile_payment', 'Pago Móvil'),
                        ('zelle', 'Zelle'),
                        ('binance', 'Binance Pay'),
                        ('cash', 'Efectivo'),
                        ('check', 'Cheque'),
                        ('other', 'Otro')
                    ],
                    max_length=20,
                    verbose_name='Tipo de pago'
                )),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones para el usuario')),
                ('requires_reference', models.BooleanField(default=True, verbose_name='Requiere número de referencia')),
                ('requires_receipt', models.BooleanField(default=True, verbose_name='Requiere comprobante')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto mínimo')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto máximo')),
                ('processing_time_hours', models.IntegerField(default=24, verbose_name='Tiempo de procesamiento (horas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['order', 'name'],
            },
        ),
        
        # Crear modelo CompanyBankAccount
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('account_type', models.CharField(
                    choices=[
                        ('checking', 'Cuenta Corriente'),
                        ('savings', 'Cuenta de Ahorros'),
                        ('business', 'Cuenta Empresarial')
                    ],
                    max_length=20,
                    verbose_name='Tipo de cuenta'
                )),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de cuenta')),
                ('account_holder', models.CharField(max_length=200, verbose_name='Titular de la cuenta')),
                ('routing_number', models.CharField(blank=True, max_length=50, verbose_name='Número de ruta/ABA')),
                ('currency', models.CharField(
                    choices=[
                        ('VES', 'Bolívares (VES)'),
                        ('USD', 'Dólares (USD)'),
                        ('EUR', 'Euros (EUR)')
                    ],
                    default='USD',
                    max_length=3,
                    verbose_name='Moneda'
                )),
                ('identification_number', models.CharField(blank=True, max_length=50, verbose_name='RIF/Cédula titular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de notificaciones')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, verbose_name='Cuenta principal')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones especiales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria de la Empresa',
                'verbose_name_plural': 'Cuentas Bancarias de la Empresa',
                'ordering': ['-is_default', 'bank_name'],
            },
        ),
    ] 