# Generated by Django 4.2.10 on 2025-06-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0003_add_payment_methods'),
    ]

    operations = [
        # Agregar relación ManyToMany entre CompanyBankAccount y PaymentMethod
        migrations.AddField(
            model_name='companybankaccount',
            name='payment_methods',
            field=models.ManyToManyField(
                blank=True,
                to='financing.paymentmethod',
                verbose_name='Métodos de pago asociados'
            ),
        ),
    ] 