# Generated by Django 4.2.10 on 2025-06-06 01:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_is_profile_complete'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financing', '0004_add_payment_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('under_review', 'En Revisión'), ('documentation_required', 'Documentación Requerida'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], max_length=30, verbose_name='Estado anterior')),
                ('to_status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('under_review', 'En Revisión'), ('documentation_required', 'Documentación Requerida'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], max_length=30, verbose_name='Estado nuevo')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='DownPaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de inicial (ej: 30.00)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en el simulador')),
            ],
            options={
                'verbose_name': 'Opción de Inicial',
                'verbose_name_plural': 'Opciones de Inicial',
                'ordering': ['order', 'percentage'],
            },
        ),
        migrations.CreateModel(
            name='FinancingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración Principal', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Financiamiento',
                'verbose_name_plural': 'Configuraciones de Financiamiento',
            },
        ),
        migrations.CreateModel(
            name='FinancingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de solicitud')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('under_review', 'En Revisión'), ('documentation_required', 'Documentación Requerida'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='draft', max_length=30, verbose_name='Estado')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('down_payment_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de inicial')),
                ('down_payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de inicial')),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a financiar')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés')),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de intereses')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total a pagar')),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Frecuencia de pago')),
                ('number_of_payments', models.IntegerField(verbose_name='Número de cuotas')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de cada cuota')),
                ('employment_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de empleo')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso mensual')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='applications/income/%Y/%m/', verbose_name='Comprobante de ingresos')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='applications/ids/%Y/%m/', verbose_name='Documento de identidad')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='applications/address/%Y/%m/', verbose_name='Comprobante de domicilio')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas de revisión')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_applications', to='users.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Solicitud de Financiamiento',
                'verbose_name_plural': 'Solicitudes de Financiamiento',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_application', 'Can approve financing application'), ('can_reject_application', 'Can reject financing application')],
            },
        ),
        migrations.CreateModel(
            name='FinancingTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField(help_text='Número de meses')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en el simulador')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_terms', to='financing.financingconfiguration')),
            ],
            options={
                'verbose_name': 'Plazo de Financiamiento',
                'verbose_name_plural': 'Plazos de Financiamiento',
                'ordering': ['order', 'months'],
            },
        ),
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('product_selection', 'Selección de Producto'), ('down_payment', 'Monto Inicial'), ('financing_term', 'Plazo de Financiamiento'), ('payment_frequency', 'Frecuencia de Pago'), ('general', 'Ayuda General')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Puede usar HTML para formato')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Texto de Ayuda',
                'verbose_name_plural': 'Textos de Ayuda',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transferencia Bancaria'), ('mobile_payment', 'Pago Móvil'), ('zelle', 'Zelle'), ('binance', 'Binance Pay'), ('cash', 'Efectivo'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('payment_type', models.CharField(choices=[('initial', 'Pago Inicial'), ('installment', 'Cuota Mensual'), ('late_fee', 'Mora'), ('penalty', 'Penalización'), ('partial', 'Pago Parcial'), ('adjustment', 'Ajuste'), ('refund', 'Reembolso')], max_length=20, verbose_name='Tipo de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Verificación'), ('verified', 'Verificado y Aprobado'), ('rejected', 'Rechazado'), ('processing', 'En Proceso de Verificación'), ('requires_review', 'Requiere Revisión Manual')], default='pending', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('payment_date', models.DateTimeField(verbose_name='Fecha del Pago')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('reference_number', models.CharField(blank=True, help_text='Número de referencia del banco o sistema de pago', max_length=100, verbose_name='Número de Referencia')),
                ('transaction_id', models.CharField(blank=True, help_text='ID único de la transacción (para Zelle, Binance, etc.)', max_length=100, verbose_name='ID de Transacción')),
                ('sender_bank', models.CharField(blank=True, max_length=100, verbose_name='Banco Emisor')),
                ('sender_account', models.CharField(blank=True, max_length=50, verbose_name='Cuenta Emisora')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Emisor')),
                ('sender_identification', models.CharField(blank=True, max_length=50, verbose_name='Cédula/RIF Emisor')),
                ('receipt_file', models.FileField(blank=True, help_text='Captura de pantalla o PDF del comprobante', null=True, upload_to='payments/receipts/%Y/%m/%d/', verbose_name='Comprobante de Pago')),
                ('customer_notes', models.TextField(blank=True, help_text='Comentarios adicionales del cliente sobre el pago', verbose_name='Notas del Cliente')),
                ('admin_notes', models.TextField(blank=True, help_text='Comentarios internos sobre la verificación', verbose_name='Notas del Administrador')),
                ('rejection_reason', models.TextField(blank=True, help_text='Razón específica si el pago fue rechazado', verbose_name='Motivo de Rechazo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financing.financingrequest', verbose_name='Solicitud de Financiamiento')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
                'permissions': [('can_verify_payment', 'Puede verificar pagos'), ('can_reject_payment', 'Puede rechazar pagos'), ('can_view_all_payments', 'Puede ver todos los pagos')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payments/attachments/%Y/%m/%d/', verbose_name='Archivo Adjunto')),
                ('file_type', models.CharField(blank=True, help_text='Detectado automáticamente', max_length=50, verbose_name='Tipo de Archivo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción del Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='financing.payment', verbose_name='Pago')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto de Pago',
                'verbose_name_plural': 'Archivos Adjuntos de Pagos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en el simulador')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_frequencies', to='financing.financingconfiguration')),
            ],
            options={
                'verbose_name': 'Frecuencia de Pago',
                'verbose_name_plural': 'Frecuencias de Pago',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField(verbose_name='Número de cuota')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado')),
                ('days_late', models.IntegerField(default=0, verbose_name='Días de atraso')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cargo por mora')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='financing.financingrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Cuota Programada',
                'verbose_name_plural': 'Cuotas Programadas',
                'ordering': ['application', 'payment_number'],
                'unique_together': {('application', 'payment_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='URL de la imagen del producto')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='financing.productcategory')),
            ],
            options={
                'verbose_name': 'Producto del Simulador',
                'verbose_name_plural': 'Productos del Simulador',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='calculatormode',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Modalidad de Calculadora', 'verbose_name_plural': 'Modalidades de Calculadora'},
        ),
        migrations.AlterModelOptions(
            name='financingplan',
            options={'ordering': ['name'], 'verbose_name': 'Plan de Financiamiento', 'verbose_name_plural': 'Planes de Financiamiento'},
        ),
        migrations.RemoveField(
            model_name='calculatormode',
            name='max_contribution_percentage',
        ),
        migrations.RemoveField(
            model_name='calculatormode',
            name='max_term_months',
        ),
        migrations.RemoveField(
            model_name='calculatormode',
            name='min_contribution_percentage',
        ),
        migrations.RemoveField(
            model_name='calculatormode',
            name='min_term_months',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='adjudication_percentage',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='max_initial_percentage',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='max_term',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='min_initial_percentage',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='min_term',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='financingplan',
            name='requirements',
        ),
        migrations.AddField(
            model_name='calculatormode',
            name='available_down_payments',
            field=models.TextField(blank=True, help_text='Porcentajes de inicial disponibles separados por coma (ej: 30,40,50,60)', verbose_name='Porcentajes de inicial disponibles'),
        ),
        migrations.AddField(
            model_name='calculatormode',
            name='available_terms',
            field=models.TextField(blank=True, help_text='Plazos disponibles en meses separados por coma (ej: 6,12,18,24)', verbose_name='Plazos disponibles'),
        ),
        migrations.AddField(
            model_name='calculatormode',
            name='max_initial_contribution',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Aporte inicial máximo (ej: 15.00)', max_digits=5, verbose_name='Aporte inicial máximo (%)'),
        ),
        migrations.AddField(
            model_name='calculatormode',
            name='min_initial_contribution',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Aporte inicial mínimo (ej: 10.00)', max_digits=5, verbose_name='Aporte inicial mínimo (%)'),
        ),
        migrations.AddField(
            model_name='calculatormode',
            name='order',
            field=models.IntegerField(default=0, help_text='Orden de aparición'),
        ),
        migrations.AddField(
            model_name='financingplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingplan',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=999999, max_digits=10, verbose_name='Monto máximo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingplan',
            name='max_term_months',
            field=models.IntegerField(default=24, verbose_name='Plazo máximo en meses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingplan',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto mínimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingplan',
            name='min_down_payment_percentage',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje mínimo de inicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financingplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calculatormode',
            name='adjudication_percentage',
            field=models.DecimalField(decimal_places=2, default=45.0, help_text='Porcentaje de adjudicación para compra programada (ej: 45.00)', max_digits=5, verbose_name='Porcentaje de adjudicación'),
        ),
        migrations.AlterField(
            model_name='calculatormode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calculatormode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calculatormode',
            name='initial_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Cuota inicial fija (ej: 5.00)', max_digits=5, verbose_name='Cuota inicial (%)'),
        ),
        migrations.AlterField(
            model_name='calculatormode',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa de interés anual (0 para sin intereses)', max_digits=5, verbose_name='Tasa de interés anual (%)'),
        ),
        migrations.AlterField(
            model_name='calculatormode',
            name='mode_type',
            field=models.CharField(choices=[('programada', 'Compra Programada'), ('credito', 'Crédito Inmediato')], max_length=20, unique=True, verbose_name='Tipo de modalidad'),
        ),
        migrations.AlterField(
            model_name='calculatormode',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la modalidad'),
        ),
        migrations.AlterField(
            model_name='calculatormode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='financingplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés anual %'),
        ),
        migrations.AlterField(
            model_name='financingplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del plan'),
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='financing.paymentschedule', verbose_name='Cuota Programada'),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_payments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='financingrequest',
            name='financing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financing.financingplan', verbose_name='Plan de financiamiento'),
        ),
        migrations.AddField(
            model_name='financingrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='financingrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='downpaymentoption',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='down_payment_options', to='financing.financingconfiguration'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='financing.financingrequest', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por'),
        ),
    ]
