# Generated by Django 4.2.10 on 2025-06-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0004_add_payment_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(null=True, blank=True, verbose_name='Fecha de Verificación'),
        ),
    ] 