# Generated by Django 4.2.10 on 2025-06-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0005_add_verified_at_field'),
        ('financing', '0006_add_payment_missing_fields'),
    ]

    operations = [
    ]
