# Generated by Django 4.2.10 on 2025-06-10 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0007_merge_20250605_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 10, 0, 39, 30, 197276, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
    ]
