# Generated by Django 4.2.10 on 2025-07-06 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financing', '0020_add_user_agent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas generales sobre el pago', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Comentarios internos sobre la verificación', verbose_name='Notas del Administrador'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Comentarios adicionales del cliente sobre el pago', verbose_name='Notas del Cliente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Captura de pantalla o PDF del comprobante', null=True, upload_to='payments/receipts/%Y/%m/%d/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Número de referencia del banco o sistema de pago', max_length=100, null=True, verbose_name='Número de Referencia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Razón específica si el pago fue rechazado', verbose_name='Motivo de Rechazo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta Emisora'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco Emisor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_identification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula/RIF Emisor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Emisor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_payments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID único de la transacción (para Zelle, Binance, etc.)', max_length=100, null=True, verbose_name='ID de Transacción'),
        ),
    ]
