# Generated by Django 4.2.10 on 2025-10-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0025_convert_to_llevo_amounts'),
        ('financing', '0026_fix_payment_fields'),
    ]

    operations = [
    ]
