# Generated by Django 4.2.10 on 2025-12-14 03:44
# Migración editada para evitar conflictos con campos existentes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0029_add_llevo_fields_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='amount_llevos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto en LLEVOS'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_window_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin ventana sin penalizacion'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_window_start',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio ventana de pago'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto penalizacion (USD)'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='penalty_applied',
            field=models.BooleanField(default=False, verbose_name='Penalizacion aplicada'),
        ),
    ]
