# Generated by Django 4.2.10 on 2025-05-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='context_data',
            field=models.TextField(default='{}', help_text='Datos de contexto en formato JSON'),
        ),
    ]
