# Generated by Django 4.2.20 on 2025-04-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(max_length=50, verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen principal')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('features', models.JSONField(help_text='Lista de características destacadas', verbose_name='Características')),
                ('specs_general', models.JSONField(blank=True, null=True, verbose_name='Especificaciones generales')),
                ('specs_engine', models.JSONField(blank=True, null=True, verbose_name='Especificaciones del motor')),
                ('specs_comfort', models.JSONField(blank=True, null=True, verbose_name='Especificaciones de confort')),
                ('specs_safety', models.JSONField(blank=True, null=True, verbose_name='Especificaciones de seguridad')),
                ('stock', models.IntegerField(default=0, verbose_name='Disponibilidad')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-featured', 'name'],
            },
        ),
    ]
