# Generated by Django 4.2.10 on 2025-08-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_llevo_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_llevo',
            field=models.PositiveIntegerField(blank=True, help_text='Precio en LLEVO (número entero)', null=True, verbose_name='Precio (LLEVO)'),
        ),
    ]
