# Generated by Django 4.2.10 on 2025-09-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_inicial_llevos_field'),
        ('products', '0003_alter_product_price_llevo'),
    ]

    operations = [
    ]
