# Generated by Django 4.2.10 on 2025-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20250901_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cuota_mensual_llevos',
            field=models.PositiveIntegerField(blank=True, help_text='Cuota mensual específica en LLEVO para 24 meses - si está vacío se calcula automáticamente', null=True, verbose_name='Cuota Mensual (LLEVO)'),
        ),
    ]
