# Generated by Django 4.2.10 on 2025-09-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cuota_mensual_llevos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(default=False, help_text='Marcar si el producto no está disponible (no se mostrará en el catálogo)', verbose_name='Sin Stock'),
        ),
    ]
